### ISSUE TITLE
最初の読み込み時に2個目のエリアが描画されない

### ISSUE THREAD

**Issue by ogaksk** [artdkt/dkt_real_web#4]
draw()まわりか

**Comment by kinescript** [comment]
リサイズイベントのバインドと同時にwindowResizeHandler関数を呼んでたのでjsonが来る前にdrawしてました。https://github.com/artdkt/dkt_real_web/issues/1 と一緒に治します。

**Comment by kinescript** [comment]
原因全然ちがいました。初期化時にRaphaelのpaperサイズが正しく設定されていなかったっぽいです。
描画直前にブラウザサイズを取得してpaperをsetsizeするように修正しました。

**Comment by ogaksk** [comment]
えっそうなんだ....  了解です
